######################################################################
# Automatically generated by qmake (2.01a) Fri Feb 8 18:53:29 2013
######################################################################

TEMPLATE = app
QT += declarative
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
RESOURCES += res.qrc
